debug upgrade
doxiaodong/builder pull request #2
Opened 2017-12-15 11:04 UTC by nighca

修正了 upgrade 之后的一些问题：

1. 用回 qiniu@6.x，7.x API 改了好多，不想搞了...
2. debug svg-sprite，配置成跟先前一致的行为
3. debug 了 publicPath 的逻辑，现在更科学一点了

2017-12-26 03:23 UTC, doxiaodong requested changes

2017-12-26 03:23 UTC, doxiaodong commented on lib/webpack-config/addons/add-transform.js
> +              options: {
这里在 `tsconfig.json` 里添加 `"moduleResolution": "node"` 试试

2017-12-26 03:23 UTC, doxiaodong commented on lib/webpack-config/addons/add-transform.js
>                loader: 'svg-sprite',
还有所有的这些loader最后会统一加上 '-loader' 么

2017-12-26 03:29 UTC, nighca commented on lib/webpack-config/addons/add-transform.js
>                loader: 'svg-sprite',
会，在 `makeRule` 里

2017-12-26 06:20 UTC, nighca commented on lib/webpack-config/addons/add-transform.js
> +              options: {
@doxiaodong 我看 [`moduleResolution`](http://www.typescriptlang.org/docs/handbook/module-resolution.html) 只影响 ts 找 module 实现的策略，没说会影响对 ES module 格式转换的行为啊

2018-01-02 09:28 UTC, nighca commented
@doxiaodong 我改了 samples 里 ts 里引入 svg 文件的方式，这边就不用去配置 svg-sprite
 的 `esModule` 了，再帮 review 下

2018-01-02 13:31 UTC, doxiaodong commented
ok，看起来可以，不过这个合进去的话，你那边要改不少代码吧

2018-01-02 13:33 UTC, nighca commented
还好，自从公司没了设计师，图片就用得很少了…

2018-01-02 13:37 UTC, doxiaodong commented
墙都不服，那我合了

2018-01-02 13:37 UTC, doxiaodong approved these changes

2018-01-02 13:37 UTC, merged